spring.application.name=discovery-service
server.port=8761

eureka.client.register-with-eureka=false

info.app.name=${spring.application.name}
info.app.description=Servico de registro de microservice com Eureka
info.app.autor=Guilherme Matte Embarach

#personalizacao do endpoint /actuator/info
eureka.instance.metadata-map.github.repo=guimattee/microservices-java