spring.application.name=greeting-service
server.port=8080
greeting-service.greeting= Hello
greeting-service.default-name= World

spring.profiles.active=es


management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.endpoint.env.show-values=always

spring.config.import=optional:configserver:http://localhost:8887/

eureka.client.service-url.default-zone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.client.healthcheck.enabled=true

#exibe informacoes do endpoint no actuator
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.description=Servico para suporte internalizado
info.app.autor=Guilherme Matte Embarach

#personalizacao do endpoint /actuator/info
eureka.instance.metadata-map.github.repo=guimattee/microservices-java

management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true
