spring.application.name=product-service
server.port=8081

spring.datasource.url=jdbc:postgresql://localhost/bd_product
spring.datasource.username=postgres
spring.datasource.password=190207Gui

spring.jpa.hibernate.ddl-auto=none

spring.jpa.show-sql=true

spring.flyway.locations=classpath:/db_migration

eureka.client.service-url.default-zone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=always
#exibe informacoes do endpoint no actuator
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.description=Microservice java 2026
info.app.autor=guilherme

#personalizacao do endpoint /actuator/info
eureka.instance.metadata-map.github.repo=teste_git

management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true
