spring.application.name=config-service
server.port=8887

#spring.profiles.active=native
#spring.cloud.config.server.native.search-locations=classpath:/configs/{application}

spring.cloud.config.server.git.uri=https://github.com/guimattee/microservices-java.git
spring.cloud.config.server.git.default-label=main
spring.cloud.config.server.git.search-paths=/configs/{application}

eureka.client.service-url.default-zone=http://localhost:8761/eureka

eureka.instance.prefer-ip-address=true
eureka.client.healthcheck.enabled=true

management.endpoints.web.exposure.include=health,info,metrics

management.endpoint.health.show-details=always
#exibe informacoes do endpoint no actuator
management.info.env.enabled=true

info.app.name=${spring.application.name}
info.app.description=Servico de configuracao centralizada do servidor
info.app.autor=Guilherme Matte Embarach 

#personalizacao do endpoint /actuator/info
eureka.instance.metadata-map.github.repo=guimattee/microservices-java

management.endpoint.health.probes.enabled=true
management.health.defaults.enabled=true